"""AI 内容标记工具 — add_ai_marker

宪法第25条：所有 AI 辅助生成的内容必须留下标记。
提供自动为代码、文档、审核意见、commit message 添加 AI 生成标记的功能。
"""

import logging
from app.kernel.tools.protocol import SkillProtocol

logger = logging.getLogger("evoiceclaw.tool.ai_marker")


class AiMarkerTool(SkillProtocol):
    """AI 内容标记工具：为 AI 生成的内容添加来源标记"""

    @property
    def name(self) -> str:
        return "add_ai_marker"

    @property
    def description(self) -> str:
        return (
            "为 AI 辅助生成的内容添加来源标记。支持四种类型：\n"
            "- code: 在代码中添加 '# AI-generated' 注释\n"
            "- document: 在文档中添加 '> 本节由 AI 辅助生成' 引用块\n"
            "- review: 在审核意见中添加 '🤖 AI Code Reviewer' 标记\n"
            "- commit: 在 commit message 中添加 '[AI]' 标签"
        )

    @property
    def parameters_schema(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["code", "document", "review", "commit"],
                    "description": "内容类型：code（代码）、document（文档）、review（审核意见）、commit（提交消息）",
                },
                "content": {
                    "type": "string",
                    "description": "要添加标记的原始内容",
                },
                "language": {
                    "type": "string",
                    "description": "[code 类型可选] 代码语言（python/javascript/swift 等），决定注释格式",
                },
            },
            "required": ["type", "content"],
        }

    @property
    def capability_brief(self) -> str:
        return "为 AI 生成的内容添加来源标记（宪法第25条）"

    async def execute(self, arguments: dict) -> str:
        content_type = arguments.get("type", "")
        content = arguments.get("content", "")
        language = arguments.get("language", "python")

        if not content:
            return "错误：请提供要标记的内容"

        if content_type == "code":
            return self._mark_code(content, language)
        elif content_type == "document":
            return self._mark_document(content)
        elif content_type == "review":
            return self._mark_review(content)
        elif content_type == "commit":
            return self._mark_commit(content)
        else:
            return f"错误：未知类型 '{content_type}'，支持: code/document/review/commit"

    def _mark_code(self, content: str, language: str) -> str:
        """为代码添加 AI 生成标记"""
        comment_styles = {
            "python": "# AI-generated by eVoiceClaw",
            "javascript": "// AI-generated by eVoiceClaw",
            "typescript": "// AI-generated by eVoiceClaw",
            "swift": "// AI-generated by eVoiceClaw",
            "java": "// AI-generated by eVoiceClaw",
            "go": "// AI-generated by eVoiceClaw",
            "rust": "// AI-generated by eVoiceClaw",
            "c": "// AI-generated by eVoiceClaw",
            "cpp": "// AI-generated by eVoiceClaw",
            "html": "<!-- AI-generated by eVoiceClaw -->",
            "css": "/* AI-generated by eVoiceClaw */",
            "sql": "-- AI-generated by eVoiceClaw",
            "yaml": "# AI-generated by eVoiceClaw",
            "shell": "# AI-generated by eVoiceClaw",
            "bash": "# AI-generated by eVoiceClaw",
        }
        marker = comment_styles.get(language.lower(), "# AI-generated by eVoiceClaw")
        logger.info("[AiMarker] 添加代码标记: language=%s", language)
        return f"{marker}\n{content}"

    def _mark_document(self, content: str) -> str:
        """为文档添加 AI 生成标记"""
        marker = "> 本节由 AI 辅助生成 (eVoiceClaw Desktop)"
        logger.info("[AiMarker] 添加文档标记")
        return f"{content}\n\n{marker}"

    def _mark_review(self, content: str) -> str:
        """为审核意见添加 AI 标记"""
        marker = "\n\n---\n🤖 AI Code Reviewer (eVoiceClaw Desktop)"
        logger.info("[AiMarker] 添加审核标记")
        return f"{content}{marker}"

    def _mark_commit(self, content: str) -> str:
        """为 commit message 添加 AI 标签"""
        if not content.startswith("[AI]"):
            content = f"[AI] {content}"
        logger.info("[AiMarker] 添加提交标记")
        return content
